### ISSUE TITLE
please update the invalid link to provide:"eachfeature"

### ISSUE THREAD

**Issue by Sean-9** [liuzhengzhe/3D-to-2D-Distillation-for-Indoor-Scene-Parsing#11]
Thank you for your awesome works!

 I want to apply your work but I found that the download link you provided is invalid, I can only blindly download "featidx2", can not find "eachfeature". We hope you will update the link to provide this data.

**Comment by liuzhengzhe** [comment]
Hi, we have updated the link. Please have a try. 

Zhengzhe
